### ISSUE TITLE
All .htmls load jquery but most don't use it

### ISSUE THREAD

**Issue by laurensdc** [osoc16/mijn-viaa#3]
Concat js files on dist & doublecheck if unused scripts are loaded (jquery @ home for example)

**Comment by igloosarecool** [comment]
If jquery isn't used that much it could be a good choice to just use vanilla JavaScript instead. Keeping it lightweight.

**Comment by laurensdc** [comment]
It is used on different pages for ajax calls though, not even sure if that can be done in vanilla JS?

**Comment by laurensdc** [comment]
I'll try this tomorrow

[https://www.sitepoint.com/guide-vanilla-ajax-without-jquery/](https://www.sitepoint.com/guide-vanilla-ajax-without-jquery/)

**Comment by laurensdc** [comment]
Maybe wait until later in development? -> If JQuery will be used for other implementations anyway it can stay

**Comment by igloosarecool** [comment]
It's your call (pun intended). Most times you'll find you can implement the same functionality without using jQuery. Thus removing a bit of bloat. In most cases you actually only use 5% of the functionality jQuery offers. Plus it's good for your js skills to write pure js. I hardly use jQuery in any small project.

There are some interesting reads on when to choose between a lib like jquery or just plain and pure js. 

Whatever you choose, I wouldn't wait until later in development because then you'll probably spend more time refactoring your jQuery into js than you would have spent writing it in the first place.

**Comment by laurensdc** [comment]
I see. I was rather thinking that, if someone later down the line would use jQuery for other implementations, it would be a 'wasted effort' to rewrite the ajax call to vanilla now.

It will be a great exercise for sure, the issue is still open so yeah I'll have another look at it asap.

Would like to know your thoughts about the load of stuff like font-awesome (<10 icons used) and a grid framework (basscss) in a project like this as well.

**Comment by igloosarecool** [comment]
Would love to discuss the above. As for font-awesome, if you're only needing a small subset: check http://fontello.com .

**Comment by laurensdc** [comment]
Resolved in f43feac
